# Extension configuration file.
# Visit the "Extension configuration file (extension.toml)" section for more details:
# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html
#

[core]
reloadable = true
order = 0

[package]
version = "0.1.0"
category = "example"
title = "HelloWorldExtension"
description = "Learning to walk"
authors = ["Jonathan"]
keywords = ["Hello","Keyword"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.kit.uiapp" = {}

# define the Python module that the extension provides
[[python.module]]
name = "mcfly"
path = "/home/chicken/Code/McFly"
public = true  # This is important -- otherwise, the HelloWorldExtension cannot see the module
searchExt = false  # If true, the import will automatically scan mcfly for all extensions available

[[python.module]]
name = "HelloWorldExtension"

[settings]
exts."HelloWorldExtension".timeout = 5
