# Extension configuration file.
# Visit the "Extension configuration file (extension.toml)" section for more details:
# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html
#

[core]
reloadable = true
order = 0

[package]
version = "0.1.0"
category = "simulation"
title = "Debug Extension"
description = "This extension loads a stage (if desired) and start code at a custom entrypoint"
authors = ["Jonathan Külz"]
keywords = ["Debugging"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/icon.png"
icon = "data/icon.png"

[dependencies]
"isaacsim.util.debug_draw" = {}
"omni.kit.uiapp" = {}
"omni.kit.debug.vscode" = {}
# The ones below are CuRobo Dependencies, actually
"omni.kit.asset_converter" = {}
"omni.kit.tool.asset_importer" = {}
"omni.isaac.asset_browser" = {}

# define the Python module that the extension provides
[[python.module]]
name = "mcfly"
path = "/home/chicken/Code/McFly"
public = true
searchExt = false

[[python.module]]
name = "DebugExtension"

[settings]
exts."DebugExtension".timeout = 5

